### PR TITLE
Code for Issue #177

### PR DESCRIPTION
**Pull request by paul-e-cooley**
Contains changes to separate ec2/s3 traffic via individual proxy settings rather than having an all or nothing approach. 

Test class requires two system properties for the proxy host/proxy port.

### CODE REVIEW

**Comment by dadoonet** [comment]
Thanks. Could you sign the cla, please?

**Comment by paul-e-cooley** [comment]
I signed the CLA about 20 minutes ago. Do you need a screenshot? Or is the db simply not up to date?

**Comment by dadoonet** [comment]
Thanks. Sounds like we have some issues with the CLA checker. Cc @karmi

**Comment by dadoonet** [comment]
Closing in favor of #191

**Pull request closed without merging**
